### ISSUE TITLE
Seeing [object Object] in skills / interests.

### ISSUE THREAD

**Issue by hstove** [wbobeirne/blockstack-hires#2]
When editing my resume, I see `[object Object]` in the text fields for skills and interests. I'm guessing this is because you're passing an object to the `value` of this component, but I haven't actually tried to track it down and fix it.

I can workaround this by selecting all text in the text field, and typing what I want it to be. Using backspace doesn't work.

![screenshot](https://cl.ly/3m3n413Q242C/Image%202018-06-06%20at%201.09.41%20PM.png)

**Comment by wbobeirne** [comment]
Good catch, this came from incorrectly setting the default value to `{}` (Which works for the form-based multi-fields like job and education, not for the single value ones.) Correctly fixed the default value to be `''` for those. Fixed by #3.
